### PR TITLE
Added upload roster file button on roster page

### PR DESCRIPTION
**Pull request by Xiangmingchen**
- Added upload roster file functionality for student
- Added NetID check for add student (individual) and add staff
Button:
image
Upload modal/popup:
image
Malformatted netid detection:
image

### CODE REVIEW

**Comment by Xiangmingchen** [comment]
Also removed the extra dump/ folder in test_data.zip file. I added accidentally last time in #83.

**Comment by Xiangmingchen** [comment]
👆🏻Looks like all the commits from when I first created a separate branch are also part of this PR. But since I merged c9807c6 into master already, only the most recent 2 commits are related.

**Comment by ayushr2** [comment]
I am late to the party but this looks great!!! Thank you @Xiangmingchen !!

**Comment by shreyas208** [comment]
Fun fact, `-` is a valid NetID character 🙂 this is an awesome feature though!

**Pull request merged**
